name: Test MCP Server - Windows

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Install dependencies
      run: |
        uv sync
        
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }
          
    - name: Run demo.py
      run: |
        Write-Host "Running MCP Server demo on Windows..."
        $ErrorActionPreference = "Stop"  # Exit on any error
        uv run python scripts/demo.py ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        if ($LASTEXITCODE -ne 0) {
          Write-Host "❌ Demo script failed with exit code $LASTEXITCODE" -ForegroundColor Red
          exit $LASTEXITCODE
        }
        Write-Host "✅ Demo script completed successfully" -ForegroundColor Green
      env:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      shell: pwsh
        
    - name: Upload test results on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: windows-test-failure-logs
        path: |
          *.log
          C:\Users\runneradmin\.azure\logs\